#!/bin/sh /etc/rc.common
USE_PROCD=1
START=98
STOP=09
start_service() {
 procd_open_instance
 procd_set_param command /usr/libexec/foxhole-history-loop
 procd_set_param respawn 3600 5 5
 procd_set_param term_timeout 5
 procd_close_instance
}
stop_service() {
 /usr/libexec/foxhole-history checkpoint >/dev/null 2>&1
}
