#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=08
start_service() {
 [ -s /etc/foxhole/inbound.json ] || return 0
 procd_open_instance
 procd_set_param command /usr/libexec/foxhole-inbound-loop
 procd_set_param respawn 3600 5 5
 procd_set_param term_timeout 5
 procd_close_instance
}
stop_service() {
 /etc/init.d/foxhole-inbound-services stop
}
